version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: '${{secrets.PRIVATE_PACKAGE_TOKEN}}'

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '13:00'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: husky
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    registries:
      - npm-registry-npm-pkg-github-com
